name: Compile Raspi Main

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install CMake
      run: sudo apt-get update && sudo apt-get install -y cmake

    - name: Build with CMake
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: main-executable
        path: ./raspi/main/build/main
