name: Compile Raspi Main

on: [push]

jobs:
  build:
    name: Build Arduino Projects
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./raspi/main/

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Change directory and run make.sh
      run: ./make.sh
