name: Compile Raspi Main

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Run make.sh
      working-directory: ./raspi/main/
      run: bash make.sh
